# Site settings
author: Cody Toney-Griffith
title: 
header-img: img/home-bg.png
email: cody.toney@gmail.com
copyright_name: Cody Toney-Griffith
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  srsvybes1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
